name: Generate SBOM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install CycloneDX CLI
        run: npm install @cyclonedx/cyclonedx-npm --save-dev

      - name: Generate SBOM
        run: npx cyclonedx-npm --output-file sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
